### PR TITLE
Finals, import optimizations

### PR DESCRIPTION
**Pull request by ProfliX**
1. Optimized imports.
2. Added some finals.

### CODE REVIEW

**Comment by Nuytemans-Dieter** [comment]
Thanks again! Looks good!

**Comment by ProfliX** [comment]
> Thanks again! Looks good!

Why dont we use normal Java style brackets style? 🙌

**Comment by Nuytemans-Dieter** [comment]
> > Thanks again! Looks good!
> 
> Why dont we use normal Java style brackets style? 🙌

I used to use the normal/recommended brackets style but found the brackets on a new line to have better readability.
Just comes down to personal preference, do you want to switch the style?

**Comment by ProfliX** [comment]
> > > Thanks again! Looks good!
> > 
> > 
> > Why dont we use normal Java style brackets style? 🙌
> 
> I used to use the normal/recommended brackets style but found the brackets on a new line to have better readability.
> Just comes down to personal preference, do you want to switch the style?

We might have a minor performance boost with normal Java style brackets,  unnecessary whitespaces are just well.. unnecessary.. (comments could be used for better readability)

**Comment by Nuytemans-Dieter** [comment]
> > > > Thanks again! Looks good!
> > > 
> > > 
> > > Why dont we use normal Java style brackets style? 🙌
> > 
> > 
> > I used to use the normal/recommended brackets style but found the brackets on a new line to have better readability.
> > Just comes down to personal preference, do you want to switch the style?
> 
> We might have a minor performance boost with normal Java style brackets, unnecessary whitespaces are just well.. unnecessary.. (comments could be used for better readability)

After compilation, there should be no performance difference whatsoever, regardless of the style being used. I think we should try to keep the code as readable as possible and only add comments when something is not straight forward (but javadoc comments are always helpful).

**Pull request merged**
